# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TWiT' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TWiT
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'SDWebImage', '~>3.8'
  pod 'SnapKit', '~> 3.0.2'
  pod 'PopupDialog', '~> 0.5'

end
